import React from 'react';
import ImageCarousel from '../component/ImageCarousel';
const Photos = () => {
  const links = [
    "https://drive.google.com/file/d/1pxub58BFlYSgVmUolbkOvse-CSGtH9rd/view?usp=sharing", //1
    "https://drive.google.com/file/d/1HpJE8nDR1Vu1ZGjRi5OH7JFfCC1YR7ht/view?usp=sharing",
    "https://drive.google.com/file/d/16c19zCf9a0VivYyhtYmiJQDHbJ_y8Fct/view?usp=sharing",
    "https://drive.google.com/file/d/1lqQw7Ga4IYdqzKHIJR7SIphQGmco8Egb/view?usp=sharing",
    "https://drive.google.com/file/d/17sugsvfT-adqlEw5YnX1HDKFzUxD9fxF/view?usp=sharing",
    "https://drive.google.com/file/d/1YazPdAPHfZhwTLWx_Sj_qAJSL-6-41zs/view?usp=sharing",
    "https://drive.google.com/file/d/1tLSGbpZmrgtZk9XeHyusdVBwZtpR3CVA/view?usp=sharing",
    "https://drive.google.com/file/d/1JcvS67jHosatqC8mAQFv8P7IbKLdnY30/view?usp=sharing",
    "https://drive.google.com/file/d/1j6c2ZKwW2zZRQzY7PMabmk0zAJTUXwpg/view?usp=sharing",
    "https://drive.google.com/file/d/19wo5tI0H-xOtiJ59c-B7QYutp5VCA51O/view?usp=sharing", //10
    "https://drive.google.com/file/d/1k-6iS6QWPY7bFxHnk3kDYkbRiAuaXvBr/view?usp=sharing",
    "https://drive.google.com/file/d/1eWT3yb4xDSVNliwzQEQ9gdqyuSyp6RX9/view?usp=sharing",
    "https://drive.google.com/file/d/17AlhcPW-MttRtA7-HhyLirqznsy0y5yg/view?usp=sharing",
    "https://drive.google.com/file/d/1Ydghg5plpljx8Ejrvt1Pc03v5uTDKjGM/view?usp=sharing",
    "https://drive.google.com/file/d/1PfM1ll-Mb3vPZFfqPxQWwixTuOGhyurr/view?usp=sharing",
    "https://drive.google.com/file/d/1x_I-MEvPfMU6WkaBf0o8nB2gysfAXE7v/view?usp=sharing",
    "https://drive.google.com/file/d/1vkTMTE6T8SmjNmp4Xnm9NShdB11WsIKL/view?usp=sharing",
    "https://drive.google.com/file/d/1JWOpNgyL-w3_XfQQ4QFL0RIBJdF225IP/view?usp=sharing",
    "https://drive.google.com/file/d/1BFVkukk7TRZqYZn2GmvQ_10zOA2dKSdd/view?usp=sharing",
    "https://drive.google.com/file/d/1Zwg_97OxgkJN1s9bkiA36uA7b8NMFFSh/view?usp=sharing",
    "https://drive.google.com/file/d/1Qfvl_OBBthTWHtI4DA9rYy6frczdIMuA/view?usp=sharing",
    "https://drive.google.com/file/d/1hkA8_cWLYJMaoJfCwonncnSk4re9Iji1/view?usp=sharing",
    "https://drive.google.com/file/d/1R3VONDzl-v37EZ6BzfRM0uPZI5tTLZCv/view?usp=sharing",
    "https://drive.google.com/file/d/14PIold7UVaRj6z4nOONmzP9ZlzWd-IuF/view?usp=sharing",
    "https://drive.google.com/file/d/1yD6ooQX0enOx-kveT1KbETOmXbuXUc49/view?usp=sharing",
    "https://drive.google.com/file/d/1h-SRzwQIWcxpUlRQ9Mv8vR0Td_oDpA1J/view?usp=sharing",
    "https://drive.google.com/file/d/1tRu1zOAej2yHwxVqc_6a1yijeL-yets1/view?usp=sharing",
    "https://drive.google.com/file/d/1L7XH7Xb1ukvQrAG1UQjbKT4B86xGWHBD/view?usp=sharing",
    "https://drive.google.com/file/d/12sbyzc7HAV8HBKBbsLEGvwCfglh_HEG5/view?usp=sharing",
    "https://drive.google.com/file/d/1I6OQxDLty6et2VEEAHCG-cGFkgMcc7_u/view?usp=sharing",
    "https://drive.google.com/file/d/1ptOmopZcmdlyPUEFe-_ujN5jDsP7nZP4/view?usp=sharing",
    "https://drive.google.com/file/d/1SJrBSnDM8BmlyZel7wd4NpdJriYED3ZI/view?usp=sharing",
    "https://drive.google.com/file/d/1omB2BZugwFzYcSfVmB1XAxIUM7P-LgPs/view?usp=sharing",
    "https://drive.google.com/file/d/1ZrnOf7-NLDU_X8mOcyDooUF6d5dxj_mZ/view?usp=sharing",
    "https://drive.google.com/file/d/1EqkoiZLmS2A9IfW7k5-mCyg-T-2uDPXe/view?usp=sharing",
    "https://drive.google.com/file/d/1XlrH-WhzYJqK8hRCBtweTDHAxKJY9Amk/view?usp=sharing",
    "https://drive.google.com/file/d/1CXoSbjQdsdz8tIWWPYK0hK0s5lHVoMPB/view?usp=sharing",
    "https://drive.google.com/file/d/1eXWoP20cSfLyeWXM8GEIGLzo1OfhEaJK/view?usp=sharing",
    "https://drive.google.com/file/d/1fS4fLwkVwgG3F6oiKc2zO9op9Hl2O0rN/view?usp=sharing",
    "https://drive.google.com/file/d/1yTefBxhaMQWrU56tP6LkG8dXa5EZwx7r/view?usp=sharing", // 40
    "https://drive.google.com/file/d/1RocEqYhwp_88vlBdOY9_nrkb5IekFlE-/view?usp=sharing",
    "https://drive.google.com/file/d/1GG9AxsqvgNlVbWpglHVikxFWCintYcF_/view?usp=sharing",
    "https://drive.google.com/file/d/1O2wVKqe47mUWdEYfHWewEL2yGQbbfoqJ/view?usp=sharing",
    "https://drive.google.com/file/d/1VEIh5QXjHMg7n1KNJ1lU96KfZ8Cpsg-3/view?usp=sharing",
    "https://drive.google.com/file/d/1hkgBO9N6gwU0HJOqCxdATKwiDLV2OPh1/view?usp=sharing",
    "https://drive.google.com/file/d/1RAw7zjv_S0YYKj_rj06RexW16x3mlfi8/view?usp=sharing",
    "https://drive.google.com/file/d/1ECj_TuTGKkViSsHnZRHrcdRUlOxwqp9h/view?usp=sharing", // 47
    "https://drive.google.com/file/d/1xGUEFOD_pT-gpuLMSia1AboXvjylSvKt/view?usp=sharing",
    "https://drive.google.com/file/d/1-zp_J_-jtqbqipEFbhaFDIsYJ4bAardY/view?usp=sharing",
    "https://drive.google.com/file/d/1mtlLUwlr2YlLG36PCYZelpu23SebNmjk/view?usp=sharing",
    "https://drive.google.com/file/d/12TDmsySUNIBlf_Y-NUoMn09T0hRZIKM6/view?usp=sharing",
    "https://drive.google.com/file/d/1eMQp_gL0-Vh-paTPu68Z81jJ_mwtUbH0/view?usp=sharing",
    "https://drive.google.com/file/d/1ntAe7tLvdHvr4ndzJ5j6RnJjVY9zi-4b/view?usp=sharing",
    "https://drive.google.com/file/d/1sukhzFU92o734riGG90F82SX9DOwPGXj/view?usp=sharing",
    "https://drive.google.com/file/d/1hNKEnRxi-OcP6DWdVycrWAqHG-0Rx6dD/view?usp=sharing",
    "https://drive.google.com/file/d/1iBD0xttIf6iqUqRdRenblQrcwEhDYrP6/view?usp=sharing",// 56
    "https://drive.google.com/file/d/1gsGFHEpVxWW4zg6Z8JVK30ZCjYZiWMEk/view?usp=sharing",
    "https://drive.google.com/file/d/1wjhtNv_6jUrikz543c_jt8svef0TSVIm/view?usp=sharing",
    "https://drive.google.com/file/d/1efZmNng03tcy5m487PxAPkMic4PS9BQ_/view?usp=sharing",
    "https://drive.google.com/file/d/1tNGR_qDowvhZeMxwigv3BhU3op8PwKHE/view?usp=sharing",
    "https://drive.google.com/file/d/1LjRJVxs_EtfF3je8eGtbmEluhabXA2_-/view?usp=sharing",
    "https://drive.google.com/file/d/1GYSuejVqOrY1CRekMx35RCQHFuvWhylB/view?usp=sharing",
    "https://drive.google.com/file/d/1bzw0Nv5XzvY0X6QyKMYdQh-qu5oxI-qv/view?usp=sharing",
    "https://drive.google.com/file/d/126Ib5JXZd9MbeOhqKO86ARjhiI2DtwXV/view?usp=sharing",
    "https://drive.google.com/file/d/1TnLOosJagpQ3wFNefgObZs0K47jT-ih_/view?usp=sharing",
    "https://drive.google.com/file/d/122Ny3pLxI3W_YN5bgYvFNNLNxn5gvs2_/view?usp=sharing",
    "https://drive.google.com/file/d/1n7scPkoC6sRrW5iOWs1Oav8BxTwDscdP/view?usp=sharing",
    "https://drive.google.com/file/d/1ZMl3JoQdPjzLIfLXZxBrc3el7rWzyZtl/view?usp=sharing",
    "https://drive.google.com/file/d/1jee3b4sOuq1vUHhaG7FvUdrObSH3X_FA/view?usp=sharing",
    "https://drive.google.com/file/d/1_kccYyYT7S5i72uectzJ9YPY_fTbA5Hy/view?usp=sharing",
    "https://drive.google.com/file/d/1pTT8ncMpqcrDFfQyitVflF5_3SoX-_kC/view?usp=sharing",
    "https://drive.google.com/file/d/1jpYm4UOj6YeXA8SphmBbGfr1doXsv4Up/view?usp=sharing",
    "https://drive.google.com/file/d/1hPrggViWAHOUACZ-AjQY8UKzCb9-go-0/view?usp=sharing",
    "https://drive.google.com/file/d/1IM808XwYb_W8priKlgu2C2gZYDDbRKd1/view?usp=sharing",
    "https://drive.google.com/file/d/1ugaamrgXSNB2OvxxO5Q_hsT_nKaaI6f-/view?usp=sharing",
    "https://drive.google.com/file/d/1PzV6SfchWX3o452Td5w0m6--bEUxF76K/view?usp=sharing",
    "https://drive.google.com/file/d/1U6ut0bEma1R9hwCwXSSCzDQHgUl5VvxT/view?usp=sharing",
    "https://drive.google.com/file/d/1oPJY9UjrEmptHG8pEiRnHBHLfJImsTFR/view?usp=sharing",
    "https://drive.google.com/file/d/1R9kedY20xczsanLx2dv6x9Z-i3COWoze/view?usp=sharing",
    "https://drive.google.com/file/d/1QN3e4RDBt8s71Nh8dqez5o7_lwztprzR/view?usp=sharing",
    "https://drive.google.com/file/d/1tSXJMt0n690z0JEPNaP7jvV-7LIhQ6va/view?usp=sharing",
    "https://drive.google.com/file/d/13t-C-O-JP3gnT7JKxzKQYaUjMu-CbNJo/view?usp=sharing",
    "https://drive.google.com/file/d/1QLNXMuypqpGxN9vZqQWCU9oFmIc6LmgN/view?usp=sharing",
    "https://drive.google.com/file/d/1oZGIM5A0zGmgIIDXWcO7h_t-ttAfleqb/view?usp=sharing",
    "https://drive.google.com/file/d/1lDNqc83BxqWXtKnbxInsB4U2FBdabODj/view?usp=sharing",
    "https://drive.google.com/file/d/1LYOUX5Pex80NW7pfvSXesclthvzny4RY/view?usp=sharing",
    "https://drive.google.com/file/d/1anP0SgApyLf2u2CqGPfSbmoZky0OGzq8/view?usp=sharing",
    "https://drive.google.com/file/d/1ngnKbdL4EGxyvyteaF9XctVSGUcTW_zv/view?usp=sharing",
    "https://drive.google.com/file/d/1f7r0FsXAoj3VK9tWeF2bTtnGoKsNJYTp/view?usp=sharing",
    "https://drive.google.com/file/d/13ASM0CEhvIMqxnVfbr0qenLoChKXbk_G/view?usp=sharing",
    "https://drive.google.com/file/d/1DrmALVOmZCCGajn-G2XwG9Z6kJkdN-2D/view?usp=sharing",
    "https://drive.google.com/file/d/1jw55ZuXHT_HQEBMke4o-Ahg_SJwnVJGv/view?usp=sharing",
    "https://drive.google.com/file/d/12ZK33aT9i1BshX8aY5NCRBEBLCn1RKLF/view?usp=sharing",
    "https://drive.google.com/file/d/1cpu8bNX8590NBd7C-yeKu-014hvsXONx/view?usp=sharing",
    "https://drive.google.com/file/d/1AamIB_e2IbU9P8LI2wAIxkW89NvM1yWO/view?usp=sharing",
    "https://drive.google.com/file/d/1qgQPGiEqRsNKQ8VHujuX3Cxv83KiR1F7/view?usp=sharing",
    "https://drive.google.com/file/d/1mgLTTIX0ad4gEj3zM6vjQf1bouaOQ_Ir/view?usp=sharing",
    "https://drive.google.com/file/d/1N9_gVKciJzM2FxM5QUE1YGUfJpBmvRrc/view?usp=sharing",
    "https://drive.google.com/file/d/1De13y4ri_qLhUb34WGBCEMkjo35H5vrC/view?usp=sharing",
    "https://drive.google.com/file/d/1tvCAFOxvxDMdCFd22TbRKmH0u8MePvbo/view?usp=sharing",
    "https://drive.google.com/file/d/1aFepVbfKY6UVMaCvqelkDUrOSjt0WFwH/view?usp=sharing",
    "https://drive.google.com/file/d/11rh8nyg2_Pl3E2Ph07ZZfmrVhGj1lupW/view?usp=sharing",
  ];
  const imageArr = Array.from({length: 102}, (_, i) => ({
    url: require(`../images/wedding/w-${i+1}.jpg`).default,
    link: links[i]
  }));
  return (
    <ImageCarousel
      title="Photos"
      imgs={imageArr}
    />
  );
};
  
export default Photos;